spring.application.name=demo
server.port=5000
spring.datasource.url=jdbc:postgresql://localhost:5432/Wissen_Final_Project
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.output.ansi.enabled=ALWAYS
spring.jpa.defer-datasource-initialization=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Email Configuration
spring.mail.host=mail.colorbycrime.com
spring.mail.port=465
spring.mail.username=verify@colorbycrime.com
#spring.mail.password="aB3d7X9kL2mP5qRt!#
#spring.mail.password=aB3d7X9kL2mP5qRt\!#

spring.mail.password=.\&@.M3(w*E=b
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.starttls.enable=false
spring.mail.properties.mail.smtp.starttls.required=false
spring.mail.properties.mail.smtp.connectiontimeout=10000
spring.mail.properties.mail.smtp.timeout=10000
spring.mail.properties.mail.smtp.writetimeout=10000
