spring.application.name=demo
server.port=5000
spring.datasource.url=jdbc:postgresql://localhost:5432/Wissen_Final_Project
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.output.ansi.enabled=ALWAYS
spring.jpa.defer-datasource-initialization=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Resend API
resend.api.key=re_KKQTb6D6_Mc9Nw2Vj5CPHYvmDAexJCug2
