spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: Rohan@2004
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

app:
  jwtSecret: "======================WissenTechSecretKey123!ThisIsLongEnoughToWork!======================"
  jwtExpirationMs: 86400000 # 24 hours
  jwtRefreshExpirationMs: 86400000

springdoc:
  api-docs:
    path: /openapi.json
  swagger-ui:
    path: /docs
    operationsSorter: method
